### ISSUE TITLE
Overmind fails in Chrome with ng-inspector plugin installed

### ISSUE THREAD

**Issue by datanotion** [geddski/overmind#11]
Dave, excellent demo at the users group.  I tracked down an issue that I don't know if you want to "fix" or not, but it would at least be worth documenting for others.

It appears that when you have this Chrome plugin installed (its an angular inspector), that it breaks OverMind:

https://chrome.google.com/webstore/detail/ng-inspector-for-angularj/aadgmnobpdmgmigaicncghmmoeflnamj

No apps will get loaded dynamically, and it generates an error in the console you can look at.

Thanks again!

**Comment by geddski** [comment]
I opened an issue on their repo and will let them take it from here and reach out if they need any help.
