### ISSUE TITLE
Dynamic app loading

### ISSUE THREAD

**Issue by rozza2058** [geddski/overmind#16]
I'd like to use overmind to dynamically load apps based on a user's login - so user A has access to home and user B has access to home and admin. At the moment this is working by leaving `overmind.apps` empty to begin with, return the apps objects that should populate it from an API and updating the global `overmind.apps` object. My problem is how to show the list of available apps in a nav. I want the `nav` app always visible so I'm assuming it has to be bootstrapped outside of overmind:

```html
<div id="overmind">
	<overmind></overmind>
</div>

<ul data-ng-app="nav" data-ng-controller="NavCtrl">
	<li data-ng-repeat="(route, obj) in apps">{{route.substr(1)}}</li>
</ul>

<div id="current-app">
	<div id="current-view"></div>
</div>
```

Because the `overmind` variable is global and outside of angular, I can't figure out how to run a digest loop in the `nav` app after the user logs in. The `overmindScope` and the `nav` app's `$rootScope` can't see each other. Is there a way to do this within overmind?

**Comment by geddski** [comment]
> I want the nav app always visible so I'm assuming it has to be bootstrapped outside of overmind

That's correct, you'd bootstrap it separately using angular.bootstrap('#nav', ['nav']) and would not register it with overmind.

As for your other question, you can use overmindScope to broadcast custom events as a means of communicating between the nav app and a dynamically loaded app.

```js
// broadcast from one app
overmindScope.$emit('my-custom-event', data);

// catch event from another app
overmindScope.$on('my-custom-event', function(data){...})
```

Let me know if that doesn't do the trick.

**Comment by rozza2058** [comment]
Does that require the overmind module to be a dependency of the nav module? Because otherwise overmindScope isn't recognised within the nav app.
