### ISSUE TITLE
require third party dependencies

### ISSUE THREAD

**Issue by jdewit** [geddski/overmind#17]
I don't see a way to set third party dependencies for a given module. 
For example, 2 out of 3 modules require D3 but are not accessed often. I could load D3 on initial page load or compile it in with each module script but that would lead to loading it unnecessarily or more than once.

I've also tried wrapping my feature modules like so:

    define(function(require) {
        require(['d3'], function() {
            angular.module('myModule', [])
            //... my app code here
        })
    });

But this causes the module to be loaded after overmind has already booted the module and throws a " Failed to instantiate module "myModule" due to:

Is there a way of doing this somehow?

Thanks!

**Comment by geddski** [comment]
Yeah just use the module as a regular dependency:

```js
define(function(require){
  require('d3');
});
```

And then in your require.js build config exclude that module (d3) from each of your build modules:

```
{
modules: [
  {
  "name": "myModule",
  "exclude": ["d3"]
  },
  {
  "name": "myOtherModule",
  "exclude": ["d3"]
  }
]
}
```

Now when either of your apps are loaded, d3.js will also be loaded but only once.
