### ISSUE TITLE
In Production?

### ISSUE THREAD

**Issue by zakarya** [geddski/overmind#24]
Is this being used in production anywhere? I'm starting a new project where I need a main (wrapper) angular app and multiple sub-apps written in angular. overmind hasn't been maintained in some time, so I was just wondering if it is still a good option. overmind looks like just what I need.

**Comment by geddski** [comment]
Hey Zack. We used it in production at Domo for a year or so then pulled it out in favor of the lazy loading that was to be part of angular 1.5. That functionality hasn't made it into Angular yet unfortunately. I don't really plan on maintaining this so you're probably better off using ocLazyLoad until Angular supports lazy loading.

**Comment by zakarya** [comment]
Awesome! Thanks Dave!
